import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Concours || EMIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen flex flex-col  font-sans ">
        
        <main className="flex-1 relative isolate ">
          <div className="fixed inset-0 -z-10" aria-hidden="true">
            <div className="absolute inset-0" />
          </div>
          <div className=" relative w-full min-h-full  ">
            {children}
          </div>
        </main>
       
      </body>
    </html>
  );
}
